# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1446, 652)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 1111, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.formLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_exp = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_exp.setFont(font)
        self.label_exp.setObjectName("label_exp")
        self.horizontalLayout_2.addWidget(self.label_exp)
        self.lineEdit_exp = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_exp.setObjectName("lineEdit_exp")
        self.horizontalLayout_2.addWidget(self.lineEdit_exp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_prj = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_prj.setFont(font)
        self.label_prj.setObjectName("label_prj")
        self.horizontalLayout_2.addWidget(self.label_prj)
        self.lineEdit_prj = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_prj.setObjectName("lineEdit_prj")
        self.horizontalLayout_2.addWidget(self.lineEdit_prj)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_prj_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_prj_2.setFont(font)
        self.label_prj_2.setObjectName("label_prj_2")
        self.horizontalLayout_2.addWidget(self.label_prj_2)
        self.lineEdit_prj_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_prj_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_prj_2.setSizePolicy(sizePolicy)
        self.lineEdit_prj_2.setObjectName("lineEdit_prj_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_prj_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 1111, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_data_dir = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_data_dir.setFont(font)
        self.label_data_dir.setObjectName("label_data_dir")
        self.horizontalLayout.addWidget(self.label_data_dir)
        self.lineEdit_data_dir = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_data_dir.setObjectName("lineEdit_data_dir")
        self.horizontalLayout.addWidget(self.lineEdit_data_dir)
        self.pushButton_data_dir = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_data_dir.sizePolicy().hasHeightForWidth())
        self.pushButton_data_dir.setSizePolicy(sizePolicy)
        self.pushButton_data_dir.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_data_dir.setFont(font)
        self.pushButton_data_dir.setObjectName("pushButton_data_dir")
        self.horizontalLayout.addWidget(self.pushButton_data_dir)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 130, 1401, 412))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_status_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_status_4.setObjectName("lineEdit_status_4")
        self.gridLayout_3.addWidget(self.lineEdit_status_4, 5, 14, 1, 1)
        self.lineEdit_status_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_status_1.setObjectName("lineEdit_status_1")
        self.gridLayout_3.addWidget(self.lineEdit_status_1, 2, 14, 1, 1)
        self.lineEdit_subid1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_subid1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid1.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_subid1.setFont(font)
        self.lineEdit_subid1.setTabletTracking(False)
        self.lineEdit_subid1.setDragEnabled(True)
        self.lineEdit_subid1.setObjectName("lineEdit_subid1")
        self.gridLayout_3.addWidget(self.lineEdit_subid1, 2, 1, 1, 1)
        self.label_box4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box4.setFont(font)
        self.label_box4.setObjectName("label_box4")
        self.gridLayout_3.addWidget(self.label_box4, 5, 0, 1, 1)
        self.label_box3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box3.setFont(font)
        self.label_box3.setObjectName("label_box3")
        self.gridLayout_3.addWidget(self.label_box3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.lineEdit_subid2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_subid2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid2.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_subid2.setFont(font)
        self.lineEdit_subid2.setDragEnabled(True)
        self.lineEdit_subid2.setObjectName("lineEdit_subid2")
        self.gridLayout_3.addWidget(self.lineEdit_subid2, 3, 1, 1, 1)
        self.lineEdit_status_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_status_3.setObjectName("lineEdit_status_3")
        self.gridLayout_3.addWidget(self.lineEdit_status_3, 4, 14, 1, 1)
        self.pushButton_Start3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start3.setFont(font)
        self.pushButton_Start3.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start3.setObjectName("pushButton_Start3")
        self.gridLayout_3.addWidget(self.pushButton_Start3, 4, 5, 1, 1)
        self.comboBox_srport_1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_1.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_1.setSizePolicy(sizePolicy)
        self.comboBox_srport_1.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_1.setObjectName("comboBox_srport_1")
        self.gridLayout_3.addWidget(self.comboBox_srport_1, 2, 15, 1, 1)
        self.pushButton_Start4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start4.setFont(font)
        self.pushButton_Start4.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start4.setObjectName("pushButton_Start4")
        self.gridLayout_3.addWidget(self.pushButton_Start4, 5, 5, 1, 1)
        self.comboBox_task1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task1.sizePolicy().hasHeightForWidth())
        self.comboBox_task1.setSizePolicy(sizePolicy)
        self.comboBox_task1.setMinimumSize(QtCore.QSize(188, 0))
        self.comboBox_task1.setObjectName("comboBox_task1")
        self.gridLayout_3.addWidget(self.comboBox_task1, 2, 2, 1, 1)
        self.label_task = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_task.sizePolicy().hasHeightForWidth())
        self.label_task.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_task.setFont(font)
        self.label_task.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task.setObjectName("label_task")
        self.gridLayout_3.addWidget(self.label_task, 0, 2, 1, 1)
        self.comboBox_task2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task2.sizePolicy().hasHeightForWidth())
        self.comboBox_task2.setSizePolicy(sizePolicy)
        self.comboBox_task2.setMinimumSize(QtCore.QSize(188, 0))
        self.comboBox_task2.setObjectName("comboBox_task2")
        self.gridLayout_3.addWidget(self.comboBox_task2, 3, 2, 1, 1)
        self.pushButton_upload_1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_upload_1.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_upload_1.setFont(font)
        self.pushButton_upload_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_1.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_upload_1.setAutoDefault(False)
        self.pushButton_upload_1.setDefault(True)
        self.pushButton_upload_1.setFlat(False)
        self.pushButton_upload_1.setObjectName("pushButton_upload_1")
        self.gridLayout_3.addWidget(self.pushButton_upload_1, 2, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 14, 1, 1)
        self.label_box1 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box1.setFont(font)
        self.label_box1.setObjectName("label_box1")
        self.gridLayout_3.addWidget(self.label_box1, 2, 0, 1, 1)
        self.pushButton_Stop3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop3.setFont(font)
        self.pushButton_Stop3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop3.setObjectName("pushButton_Stop3")
        self.gridLayout_3.addWidget(self.pushButton_Stop3, 4, 7, 1, 1)
        self.lineEdit_subid4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_subid4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid4.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_subid4.setFont(font)
        self.lineEdit_subid4.setDragEnabled(True)
        self.lineEdit_subid4.setObjectName("lineEdit_subid4")
        self.gridLayout_3.addWidget(self.lineEdit_subid4, 5, 1, 1, 1)
        self.lineEdit_subid3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_subid3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_subid3.sizePolicy().hasHeightForWidth())
        self.lineEdit_subid3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_subid3.setFont(font)
        self.lineEdit_subid3.setDragEnabled(True)
        self.lineEdit_subid3.setObjectName("lineEdit_subid3")
        self.gridLayout_3.addWidget(self.lineEdit_subid3, 4, 1, 1, 1)
        self.comboBox_task3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task3.sizePolicy().hasHeightForWidth())
        self.comboBox_task3.setSizePolicy(sizePolicy)
        self.comboBox_task3.setMinimumSize(QtCore.QSize(188, 0))
        self.comboBox_task3.setObjectName("comboBox_task3")
        self.gridLayout_3.addWidget(self.comboBox_task3, 4, 2, 1, 1)
        self.comboBox_task4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_task4.sizePolicy().hasHeightForWidth())
        self.comboBox_task4.setSizePolicy(sizePolicy)
        self.comboBox_task4.setMinimumSize(QtCore.QSize(188, 0))
        self.comboBox_task4.setObjectName("comboBox_task4")
        self.gridLayout_3.addWidget(self.comboBox_task4, 5, 2, 1, 1)
        self.pushButton_var4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var4.sizePolicy().hasHeightForWidth())
        self.pushButton_var4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var4.setFont(font)
        self.pushButton_var4.setObjectName("pushButton_var4")
        self.gridLayout_3.addWidget(self.pushButton_var4, 5, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 15, 1, 1)
        self.pushButton_Start2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start2.setFont(font)
        self.pushButton_Start2.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start2.setObjectName("pushButton_Start2")
        self.gridLayout_3.addWidget(self.pushButton_Start2, 3, 5, 1, 1)
        self.pushButton_connect_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_2.setFont(font)
        self.pushButton_connect_2.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_2.setObjectName("pushButton_connect_2")
        self.gridLayout_3.addWidget(self.pushButton_connect_2, 3, 16, 1, 1)
        self.pushButton_Stop4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop4.setFont(font)
        self.pushButton_Stop4.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop4.setObjectName("pushButton_Stop4")
        self.gridLayout_3.addWidget(self.pushButton_Stop4, 5, 7, 1, 1)
        self.pushButton_connect_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_4.setFont(font)
        self.pushButton_connect_4.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_4.setObjectName("pushButton_connect_4")
        self.gridLayout_3.addWidget(self.pushButton_connect_4, 5, 16, 1, 1)
        self.lcdNumber_Timer_BOX3 = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX3.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX3.setFont(font)
        self.lcdNumber_Timer_BOX3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX3.setAutoFillBackground(True)
        self.lcdNumber_Timer_BOX3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX3.setLineWidth(0)
        self.lcdNumber_Timer_BOX3.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX3.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX3.setObjectName("lcdNumber_Timer_BOX3")
        self.gridLayout_3.addWidget(self.lcdNumber_Timer_BOX3, 4, 6, 1, 1)
        self.pushButton_Start1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Start1.setFont(font)
        self.pushButton_Start1.setStyleSheet("background-color: rgb(28, 255, 35);")
        self.pushButton_Start1.setObjectName("pushButton_Start1")
        self.gridLayout_3.addWidget(self.pushButton_Start1, 2, 5, 1, 1)
        self.lcdNumber_Timer_BOX2 = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX2.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX2.setFont(font)
        self.lcdNumber_Timer_BOX2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX2.setAutoFillBackground(True)
        self.lcdNumber_Timer_BOX2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX2.setLineWidth(0)
        self.lcdNumber_Timer_BOX2.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX2.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX2.setObjectName("lcdNumber_Timer_BOX2")
        self.gridLayout_3.addWidget(self.lcdNumber_Timer_BOX2, 3, 6, 1, 1)
        self.pushButton_Stop2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop2.setFont(font)
        self.pushButton_Stop2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_Stop2.setObjectName("pushButton_Stop2")
        self.gridLayout_3.addWidget(self.pushButton_Stop2, 3, 7, 1, 1)
        self.pushButton_config_1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_config_1.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_1.setObjectName("pushButton_config_1")
        self.gridLayout_3.addWidget(self.pushButton_config_1, 2, 19, 1, 1)
        self.pushButton_config_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_config_2.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_2.setObjectName("pushButton_config_2")
        self.gridLayout_3.addWidget(self.pushButton_config_2, 3, 19, 1, 1)
        self.pushButton_connect_1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_1.setFont(font)
        self.pushButton_connect_1.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_1.setObjectName("pushButton_connect_1")
        self.gridLayout_3.addWidget(self.pushButton_connect_1, 2, 16, 1, 1)
        self.pushButton_upload_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_upload_4.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_upload_4.setFont(font)
        self.pushButton_upload_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_4.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_upload_4.setAutoDefault(False)
        self.pushButton_upload_4.setDefault(True)
        self.pushButton_upload_4.setFlat(False)
        self.pushButton_upload_4.setObjectName("pushButton_upload_4")
        self.gridLayout_3.addWidget(self.pushButton_upload_4, 5, 4, 1, 1)
        self.pushButton_config_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_config_4.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_4.setObjectName("pushButton_config_4")
        self.gridLayout_3.addWidget(self.pushButton_config_4, 5, 19, 1, 1)
        self.pushButton_upload_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_upload_2.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_upload_2.setFont(font)
        self.pushButton_upload_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_upload_2.setAutoDefault(False)
        self.pushButton_upload_2.setDefault(True)
        self.pushButton_upload_2.setFlat(False)
        self.pushButton_upload_2.setObjectName("pushButton_upload_2")
        self.gridLayout_3.addWidget(self.pushButton_upload_2, 3, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 6, 1, 1)
        self.comboBox_srport_4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_4.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_4.setSizePolicy(sizePolicy)
        self.comboBox_srport_4.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_4.setObjectName("comboBox_srport_4")
        self.gridLayout_3.addWidget(self.comboBox_srport_4, 5, 15, 1, 1)
        self.comboBox_srport_3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_3.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_3.setSizePolicy(sizePolicy)
        self.comboBox_srport_3.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_3.setObjectName("comboBox_srport_3")
        self.gridLayout_3.addWidget(self.comboBox_srport_3, 4, 15, 1, 1)
        self.pushButton_var3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var3.sizePolicy().hasHeightForWidth())
        self.pushButton_var3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var3.setFont(font)
        self.pushButton_var3.setObjectName("pushButton_var3")
        self.gridLayout_3.addWidget(self.pushButton_var3, 4, 8, 1, 1)
        self.lineEdit_status_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_status_2.setObjectName("lineEdit_status_2")
        self.gridLayout_3.addWidget(self.lineEdit_status_2, 3, 14, 1, 1)
        self.comboBox_srport_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_srport_2.sizePolicy().hasHeightForWidth())
        self.comboBox_srport_2.setSizePolicy(sizePolicy)
        self.comboBox_srport_2.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_srport_2.setObjectName("comboBox_srport_2")
        self.gridLayout_3.addWidget(self.comboBox_srport_2, 3, 15, 1, 1)
        self.pushButton_upload_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_upload_3.setMinimumSize(QtCore.QSize(98, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_upload_3.setFont(font)
        self.pushButton_upload_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_upload_3.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_upload_3.setAutoDefault(False)
        self.pushButton_upload_3.setDefault(True)
        self.pushButton_upload_3.setFlat(False)
        self.pushButton_upload_3.setObjectName("pushButton_upload_3")
        self.gridLayout_3.addWidget(self.pushButton_upload_3, 4, 4, 1, 1)
        self.pushButton_var2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var2.sizePolicy().hasHeightForWidth())
        self.pushButton_var2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var2.setFont(font)
        self.pushButton_var2.setObjectName("pushButton_var2")
        self.gridLayout_3.addWidget(self.pushButton_var2, 3, 8, 1, 1)
        self.lcdNumber_Timer_BOX1 = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX1.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX1.setFont(font)
        self.lcdNumber_Timer_BOX1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX1.setAutoFillBackground(True)
        self.lcdNumber_Timer_BOX1.setStyleSheet("selection-background-color: rgb(0, 0, 0);")
        self.lcdNumber_Timer_BOX1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX1.setLineWidth(0)
        self.lcdNumber_Timer_BOX1.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX1.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX1.setObjectName("lcdNumber_Timer_BOX1")
        self.gridLayout_3.addWidget(self.lcdNumber_Timer_BOX1, 2, 6, 1, 1)
        self.pushButton_config_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_config_3.setStyleSheet("background-color: rgb(241, 78, 255);")
        self.pushButton_config_3.setObjectName("pushButton_config_3")
        self.gridLayout_3.addWidget(self.pushButton_config_3, 4, 19, 1, 1)
        self.pushButton_var1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_var1.sizePolicy().hasHeightForWidth())
        self.pushButton_var1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_var1.setFont(font)
        self.pushButton_var1.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.pushButton_var1.setObjectName("pushButton_var1")
        self.gridLayout_3.addWidget(self.pushButton_var1, 2, 8, 1, 1)
        self.lcdNumber_Timer_BOX4 = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_Timer_BOX4.sizePolicy().hasHeightForWidth())
        self.lcdNumber_Timer_BOX4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcdNumber_Timer_BOX4.setFont(font)
        self.lcdNumber_Timer_BOX4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber_Timer_BOX4.setAutoFillBackground(True)
        self.lcdNumber_Timer_BOX4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_Timer_BOX4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_Timer_BOX4.setLineWidth(0)
        self.lcdNumber_Timer_BOX4.setMidLineWidth(0)
        self.lcdNumber_Timer_BOX4.setSmallDecimalPoint(False)
        self.lcdNumber_Timer_BOX4.setObjectName("lcdNumber_Timer_BOX4")
        self.gridLayout_3.addWidget(self.lcdNumber_Timer_BOX4, 5, 6, 1, 1)
        self.pushButton_Stop1 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Stop1.setFont(font)
        self.pushButton_Stop1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.pushButton_Stop1.setObjectName("pushButton_Stop1")
        self.gridLayout_3.addWidget(self.pushButton_Stop1, 2, 7, 1, 1)
        self.pushButton_connect_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_connect_3.setFont(font)
        self.pushButton_connect_3.setStyleSheet("background-color: rgb(255, 209, 115);")
        self.pushButton_connect_3.setObjectName("pushButton_connect_3")
        self.gridLayout_3.addWidget(self.pushButton_connect_3, 4, 16, 1, 1)
        self.label_box2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_box2.setFont(font)
        self.label_box2.setObjectName("label_box2")
        self.gridLayout_3.addWidget(self.label_box2, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(-530, 110, 2031, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(3, 1, 1501, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(-10, 524, 2031, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(590, 550, 691, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
        self.exportdata = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.exportdata.setObjectName("exportdata")
        self.gridLayout_6.addWidget(self.exportdata, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 2, 1, 1)
        self.resettable = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.resettable.setObjectName("resettable")
        self.gridLayout_6.addWidget(self.resettable, 0, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 0, 4, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(65)
        self.tableWidget.setRowCount(14)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(40, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(41, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(42, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(43, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(44, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(45, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(46, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(47, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(48, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(49, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(50, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(51, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(52, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(53, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(54, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(55, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(56, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(57, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(58, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(59, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(60, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(61, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(62, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(63, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(64, item)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        self.Exportdata2 = QtWidgets.QPushButton(self.tab_4)
        self.Exportdata2.setObjectName("Exportdata2")
        self.horizontalLayout_3.addWidget(self.Exportdata2)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_exp.setText(_translate("MainWindow", "Experimenter Name: "))
        self.label_prj.setText(_translate("MainWindow", "Project: "))
        self.label_prj_2.setText(_translate("MainWindow", "Session"))
        self.label_data_dir.setText(_translate("MainWindow", "Data dir:"))
        self.pushButton_data_dir.setText(_translate("MainWindow", "..."))
        self.label_box4.setText(_translate("MainWindow", "BOX 4"))
        self.label_box3.setText(_translate("MainWindow", "BOX 3"))
        self.label.setText(_translate("MainWindow", "SUBJECT ID"))
        self.pushButton_Start3.setText(_translate("MainWindow", "START"))
        self.pushButton_Start4.setText(_translate("MainWindow", "START"))
        self.label_task.setText(_translate("MainWindow", "TASK"))
        self.pushButton_upload_1.setText(_translate("MainWindow", "Upload"))
        self.label_4.setText(_translate("MainWindow", "Status"))
        self.label_box1.setText(_translate("MainWindow", "BOX 1"))
        self.pushButton_Stop3.setText(_translate("MainWindow", "STOP"))
        self.pushButton_var4.setText(_translate("MainWindow", "Variables"))
        self.label_3.setText(_translate("MainWindow", "Serial Port"))
        self.pushButton_Start2.setText(_translate("MainWindow", "START"))
        self.pushButton_connect_2.setText(_translate("MainWindow", "Connect"))
        self.pushButton_Stop4.setText(_translate("MainWindow", "STOP"))
        self.pushButton_connect_4.setText(_translate("MainWindow", "Connect"))
        self.pushButton_Start1.setText(_translate("MainWindow", "START"))
        self.pushButton_Stop2.setText(_translate("MainWindow", "STOP"))
        self.pushButton_config_1.setText(_translate("MainWindow", "Config"))
        self.pushButton_config_2.setText(_translate("MainWindow", "Config"))
        self.pushButton_connect_1.setText(_translate("MainWindow", "Connect"))
        self.pushButton_upload_4.setText(_translate("MainWindow", "Upload"))
        self.pushButton_config_4.setText(_translate("MainWindow", "Config"))
        self.pushButton_upload_2.setText(_translate("MainWindow", "Upload"))
        self.label_2.setText(_translate("MainWindow", "Timer"))
        self.pushButton_var3.setText(_translate("MainWindow", "Variables"))
        self.pushButton_upload_3.setText(_translate("MainWindow", "Upload"))
        self.pushButton_var2.setText(_translate("MainWindow", "Variables"))
        self.pushButton_config_3.setText(_translate("MainWindow", "Config"))
        self.pushButton_var1.setText(_translate("MainWindow", "Variables"))
        self.pushButton_Stop1.setText(_translate("MainWindow", "STOP"))
        self.pushButton_connect_3.setText(_translate("MainWindow", "Connect"))
        self.label_box2.setText(_translate("MainWindow", "BOX 2"))
        self.exportdata.setText(_translate("MainWindow", "Export Data"))
        self.resettable.setText(_translate("MainWindow", "Reset Table"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.Exportdata2.setText(_translate("MainWindow", "Export DATA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

